package com.schwarz.crystalcore.processing.model

import com.schwarz.crystalcore.ICodeGenerator
import com.schwarz.crystalcore.ILogger
import com.schwarz.crystalcore.ISettings
import com.schwarz.crystalcore.documentation.DocumentationGenerator
import com.schwarz.crystalcore.documentation.EntityRelationshipGenerator
import com.schwarz.crystalcore.generation.model.CommonInterfaceGeneration
import com.schwarz.crystalcore.generation.model.EntityGeneration
import com.schwarz.crystalcore.generation.model.SchemaGeneration
import com.schwarz.crystalcore.generation.model.TypeConverterExporterObjectGeneration
import com.schwarz.crystalcore.generation.model.TypeConverterObjectGeneration
import com.schwarz.crystalcore.generation.model.WrapperGeneration
import com.schwarz.crystalcore.meta.SchemaGenerator
import com.schwarz.crystalcore.model.entity.BaseEntityHolder
import com.schwarz.crystalcore.model.entity.SchemaClassHolder
import com.schwarz.crystalcore.model.field.CblFieldHolder
import com.schwarz.crystalcore.model.source.ISourceModel
import com.schwarz.crystalcore.model.typeconverter.TypeConverterHolder
import com.schwarz.crystalcore.model.typeconverter.TypeConverterHolderForEntityGeneration
import com.schwarz.crystalcore.processing.Worker
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec

class ModelWorker<T>(
    override val logger: ILogger<T>,
    override val codeGenerator: ICodeGenerator,
    override val settings: ISettings,
    override val workSet: ModelWorkSet<T>,
    // True for incremental KSP processing: reprocessedFilePaths may then be
    // only a subset of the compilation. The doc/schema side outputs merge with
    // the previous run instead of being rebuilt, and generation is limited to
    // models originating from reprocessed files — the outputs of untouched
    // sources still exist because KSP only deletes the outputs of dirty
    // sources, and createNewFile rejects existing files.
    private val incremental: Boolean = false,
    // False when the frontend persists the converter world across incremental
    // runs (see TypeConverterRegistry in crystal-map-ksp): converter/exporter
    // outputs may then stay isolating and no importer anchors are needed,
    // keeping incremental dirty sets small. True forces the aggregating
    // fallback, where KSP re-collects every converter source on any change.
    private val converterOutputsAggregating: Boolean = true,
    // Previously generated side-output entries whose origin is in this set are
    // purged when the run no longer produces them.
    private val reprocessedFilePaths: Set<String> = emptySet(),
    // Sources whose generated outputs do not exist on disk: dirty files (KSP
    // deleted their outputs) plus files first handed in by a later round
    // (generated by a co-running processor). In incremental mode only models
    // originating from these may be generated.
    private val regenerationFilePaths: Set<String> = emptySet(),
    // Extracts a stable file path from a platform originating-file object
    // (KSFile for KSP); null when the platform cannot provide one (kapt).
    private val originFilePath: (Any) -> String? = { null },
) : Worker<ModelWorkSet<T>, T> {
    private var documentationGenerator: DocumentationGenerator? = null
    private var entityRelationshipGenerator: EntityRelationshipGenerator? = null
    private var schemaGenerator: SchemaGenerator? = null

    override fun init() {
        val warn: (String) -> Unit = { logger.warn(it, null) }
        settings.documentationPath?.let {
            documentationGenerator =
                DocumentationGenerator(it, settings.documentationFilename ?: "default.html", warn)
        }
        settings.schemaPath?.let {
            schemaGenerator =
                SchemaGenerator(
                    it,
                    settings.schemaFilename ?: "schema.json",
                    warn,
                )
        }

        settings.entityRelationshipPath?.let {
            entityRelationshipGenerator =
                EntityRelationshipGenerator(it, settings.entityRelationshipFilename ?: "default.gv", warn)
        }
    }

    override fun doWork(
        workSet: ModelWorkSet<T>,
        useSuspend: Boolean,
    ) {
        val typeConvertersByConvertedClass: Map<TypeName, TypeConverterHolderForEntityGeneration> =
            (workSet.typeConverters + workSet.importedTypeConverters).associateBy {
                it.domainClassTypeName
            }

        // Type converters are a global registry: entities anywhere in the
        // module may need any converter, but an incremental run only hands the
        // processor its dirty files. Unless the frontend persists the converter
        // world (converterOutputsAggregating = false), their outputs and the
        // importer anchors below are aggregating — KSP then invalidates them on
        // any change and reprocesses every converter source, keeping the
        // registry complete.
        workSet.typeConverters.forEach {
            if (needsRegeneration(it.originatingFiles)) {
                codeGenerator.generate(
                    TypeConverterObjectGeneration.generateTypeConverterObject(it),
                    settings,
                    it.originatingFiles,
                    aggregating = converterOutputsAggregating,
                )
            }
        }

        workSet.typeConverterExporters.forEach {
            if (needsRegeneration(it.originatingFiles)) {
                val exporterOrigins = it.originatingFiles +
                    workSet.typeConverters.flatMap { tc -> tc.originatingFiles }
                codeGenerator.generate(
                    TypeConverterExporterObjectGeneration.generateTypeConverterExporterObject(
                        it,
                        workSet.typeConverters,
                    ),
                    settings,
                    exporterOrigins,
                    aggregating = converterOutputsAggregating,
                )
            }
        }

        // Importers have no natural output, so without one KSP would never
        // reprocess them incrementally and the imported converters would
        // vanish from the registry. Only needed in aggregating mode; with a
        // persisted registry the importers are restored by qualified name, and
        // kapt hands over the full compilation every run anyway.
        if (incremental && converterOutputsAggregating) {
            workSet.typeConverterImporters.forEach { importer ->
                if (needsRegeneration(importer.originatingFiles)) {
                    codeGenerator.generate(
                        importerAnchor(importer),
                        settings,
                        importer.originatingFiles,
                        aggregating = true,
                    )
                }
            }
        }

        val generatedInterfaces = mutableSetOf<String>()

        for (baseModelHolder in workSet.bases) {
            if (needsRegeneration(baseModelHolder.allOriginatingFiles)) {
                generateInterface(
                    generatedInterfaces,
                    baseModelHolder,
                    useSuspend,
                    typeConvertersByConvertedClass,
                )
            }
        }

        processAndFixAccessors(
            workSet.entities,
            generatedInterfaces,
            useSuspend,
            typeConvertersByConvertedClass,
        ) {
            EntityGeneration().generateModel(it, useSuspend, typeConvertersByConvertedClass)
        }

        processAndFixAccessors(
            workSet.wrappers,
            generatedInterfaces,
            useSuspend,
            typeConvertersByConvertedClass,
        ) {
            WrapperGeneration().generateModel(it, useSuspend, typeConvertersByConvertedClass)
        }

        process(workSet.schemas) {
            SchemaGeneration().generateModel(
                it,
                workSet.schemaClassPaths,
                typeConvertersByConvertedClass,
            )
        }

        documentationGenerator?.generate(incremental, reprocessedFilePaths)
        entityRelationshipGenerator?.generate(incremental, reprocessedFilePaths)
        schemaGenerator?.generate(incremental, reprocessedFilePaths)
    }

    private fun process(
        schemaModels: List<SchemaClassHolder<T>>,
        generate: (SchemaClassHolder<T>) -> FileSpec,
    ) {
        for (model in schemaModels) {
            if (!needsRegeneration(model.allOriginatingFiles)) {
                continue
            }
            val sourcePaths = sourcePathsOf(model)
            documentationGenerator?.addEntitySegments(model, sourcePaths)
            schemaGenerator?.addEntity(model, sourcePaths)
            entityRelationshipGenerator?.addEntityNodes(model, sourcePaths)
            generate(model).apply {
                codeGenerator.generate(this, settings, model.allOriginatingFiles, aggregating = false)
            }
        }
    }

    private fun <E : BaseEntityHolder<T>> processAndFixAccessors(
        models: List<E>,
        generatedInterfaces: MutableSet<String>,
        useSuspend: Boolean,
        typeConvertersByConvertedClass: Map<TypeName, TypeConverterHolderForEntityGeneration>,
        generate: (E) -> FileSpec,
    ) {
        for (model in models) {
            if (!needsRegeneration(model.allOriginatingFiles)) {
                continue
            }
            generateInterface(
                generatedInterfaces,
                model,
                useSuspend,
                typeConvertersByConvertedClass,
            )
            val sourcePaths = sourcePathsOf(model)
            documentationGenerator?.addEntitySegments(model, sourcePaths)
            schemaGenerator?.addEntity(model, sourcePaths)
            entityRelationshipGenerator?.addEntityNodes(model, sourcePaths)
            val tcOrigins = usedTypeConverterOrigins(model, typeConvertersByConvertedClass)
            val origins = model.allOriginatingFiles + tcOrigins
            generate(model).apply {
                if (model.generateAccessors.isNotEmpty()) {
                    codeGenerator.generateAndFixAccessors(
                        this,
                        model.generateAccessors,
                        settings,
                        origins,
                        aggregating = false,
                    )
                } else {
                    codeGenerator.generate(
                        this,
                        settings,
                        origins,
                        aggregating = false,
                    )
                }
            }
        }
    }

    private fun generateInterface(
        generatedInterfaces: MutableSet<String>,
        holder: BaseEntityHolder<T>,
        useSuspend: Boolean,
        typeConvertersByConvertedClass: Map<TypeName, TypeConverterHolderForEntityGeneration>,
    ) {
        if (generatedInterfaces
                .contains(
                    "${holder.sourcePackage}.${holder.sourceClazzSimpleName}",
                ).not()
        ) {
            codeGenerator.generate(
                CommonInterfaceGeneration().generateModel(
                    holder,
                    useSuspend,
                    typeConvertersByConvertedClass,
                ),
                settings,
                holder.allOriginatingFiles,
                aggregating = false,
            )
            generatedInterfaces.add("${holder.sourcePackage}.${holder.sourceClazzSimpleName}")
        }
    }

    private fun importerAnchor(importer: ISourceModel<T>): FileSpec {
        val name = "${importer.sourceClazzSimpleName}CrystalMapAnchor"
        return FileSpec
            .builder(importer.sourcePackage, name)
            .addType(
                TypeSpec
                    .objectBuilder(name)
                    .addModifiers(KModifier.INTERNAL)
                    .addKdoc(
                        "Aggregating KSP anchor: forces the type-converter importer to be " +
                            "reprocessed on every incremental build so the imported " +
                            "converters stay registered.",
                    ).build(),
            ).build()
    }

    // The work set may span the whole compilation (world knowledge needed for
    // validation and type resolution); only models whose own sources were
    // reprocessed have had their outputs deleted by KSP and may be regenerated.
    private fun needsRegeneration(originatingFiles: List<Any>): Boolean =
        !incremental ||
            originatingFiles.mapNotNull(originFilePath).any(regenerationFilePaths::contains)

    private fun sourcePathsOf(holder: BaseEntityHolder<T>): List<String> = holder.allOriginatingFiles.mapNotNull(originFilePath)

    private fun usedTypeConverterOrigins(
        holder: BaseEntityHolder<T>,
        typeConvertersByConvertedClass: Map<TypeName, TypeConverterHolderForEntityGeneration>,
    ): List<Any> =
        holder.allFields
            .filterIsInstance<CblFieldHolder>()
            .filter { !it.isNonConvertibleClass && !it.isTypeOfSubEntity }
            .mapNotNull { typeConvertersByConvertedClass[it.fieldType] }
            .filterIsInstance<TypeConverterHolder>()
            .flatMap { it.originatingFiles }
            .distinct()
}
