package com.schwarz.crystalksp

import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.tschuchort.compiletesting.JvmCompilationResult
import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.SourceFile
import com.tschuchort.compiletesting.configureKsp
import com.tschuchort.compiletesting.sourcesGeneratedBySymbolProcessor
import com.tschuchort.compiletesting.symbolProcessorProviders
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Verifies that crystal-map-ksp is well-behaved in KSP2 multi-round processing, i.e. when a
 * second symbol processor (like a DI processor) generates Kotlin sources in the same compilation.
 *
 * Every file generated by the companion processor triggers an extra processing round, which
 * invalidates all KSP nodes obtained from earlier rounds ("PSI has changed since creation").
 * Crystal-map must therefore never carry Resolver-derived objects across rounds.
 */
@OptIn(ExperimentalCompilerApi::class)
class MultiProcessorRoundTest {
    /**
     * Minimal stand-in for a second code-generating processor: writes one Kotlin file in the
     * first round and stays quiet afterwards.
     */
    private class CompanionProcessorProvider(
        private val fileName: String,
        private val content: String,
    ) : SymbolProcessorProvider {
        override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
            object : SymbolProcessor {
                private var generated = false

                override fun process(resolver: Resolver): List<KSAnnotated> {
                    if (!generated) {
                        generated = true
                        environment.codeGenerator
                            .createNewFile(Dependencies(false), "com.kaufland.testModels", fileName)
                            .writer()
                            .use { it.write(content) }
                    }
                    return emptyList()
                }
            }
    }

    @Test
    fun testEntityProcessingSurvivesExtraRoundFromSecondProcessor() {
        val entity =
            SourceFile.kotlin(
                "Product.kt",
                """
                package com.kaufland.testModels

                import com.schwarz.crystalapi.Entity
                import com.schwarz.crystalapi.Field
                import com.schwarz.crystalapi.Fields

                @Entity(database = "test_db")
                @Fields(
                    Field(name = "name", type = String::class),
                    Field(name = "type", type = String::class, defaultValue = "product", readonly = true),
                )
                open class Product
                """.trimIndent(),
            )

        val result =
            compileWithCompanion(
                entity,
                companionFileName = "GeneratedFactory",
                companionContent =
                    """
                    package com.kaufland.testModels

                    class GeneratedFactory
                    """.trimIndent(),
            )

        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, result.messages)
        assertTrue(
            result.sourcesGeneratedBySymbolProcessor.any { it.name == "ProductEntity.kt" },
            "expected ProductEntity.kt to be generated, got: " +
                result.sourcesGeneratedBySymbolProcessor.joinToString { it.name },
        )
    }

    @Test
    fun testEntityMayReferenceClassGeneratedByOtherProcessor() {
        // The annotation argument GeneratedBase::class is an error type in round 0 because the
        // class only comes into existence through the companion processor. It must not fail with
        // "Error type '<ERROR TYPE: GeneratedBase>' is not resolvable in the current round".
        val entity =
            SourceFile.kotlin(
                "Sub.kt",
                """
                package com.kaufland.testModels

                import com.schwarz.crystalapi.BasedOn
                import com.schwarz.crystalapi.Entity
                import com.schwarz.crystalapi.Field
                import com.schwarz.crystalapi.Fields

                @Entity(database = "test_db")
                @BasedOn(GeneratedBase::class)
                @Fields(
                    Field(name = "own_field", type = String::class),
                    Field(name = "type", type = String::class, defaultValue = "sub", readonly = true),
                )
                open class Sub
                """.trimIndent(),
            )

        val result =
            compileWithCompanion(
                entity,
                companionFileName = "GeneratedBase",
                companionContent =
                    """
                    package com.kaufland.testModels

                    import com.schwarz.crystalapi.BaseModel
                    import com.schwarz.crystalapi.Field
                    import com.schwarz.crystalapi.Fields

                    @BaseModel
                    @Fields(
                        Field(name = "generated_field", type = String::class),
                    )
                    open class GeneratedBase
                    """.trimIndent(),
            )

        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, result.messages)

        val subEntity =
            result.sourcesGeneratedBySymbolProcessor.find { it.name == "SubEntity.kt" }
        assertTrue(
            subEntity != null,
            "expected SubEntity.kt to be generated, got: " +
                result.sourcesGeneratedBySymbolProcessor.joinToString { it.name },
        )
        assertTrue(
            subEntity!!.readText().contains("generated_field"),
            "expected SubEntity.kt to inherit the field of the generated base model",
        )
    }

    private fun compileWithCompanion(
        vararg sourceFiles: SourceFile,
        companionFileName: String,
        companionContent: String,
    ): JvmCompilationResult =
        KotlinCompilation()
            .apply {
                configureKsp {
                    symbolProcessorProviders.add(CrystalProcessorProvider())
                    symbolProcessorProviders.add(
                        CompanionProcessorProvider(companionFileName, companionContent),
                    )
                }
                languageVersion = "2.1"
                sources = sourceFiles.toMutableList()
                jvmTarget = "17"
                inheritClassPath = true
            }.compile()
}
