package com.schwarz.crystalksp.generation

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.schwarz.crystalcore.ICodeGenerator
import com.schwarz.crystalcore.ISettings
import com.schwarz.crystalcore.model.accessor.CblGenerateAccessorHolder
import com.schwarz.crystalksp.ProcessingContext
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import java.io.IOException

class KSPCodeGenerator(
    private val generator: CodeGenerator,
    private val cache: GenerationCache? = null,
) : ICodeGenerator {
    data class GenerationRecord(
        val fileName: String,
        val originatingFileNames: List<String>,
        val aggregating: Boolean,
    )

    val generationRecords: MutableList<GenerationRecord> = mutableListOf()

    override fun generate(
        toGenerate: FileSpec,
        settings: ISettings,
    ) {
        generate(toGenerate, settings, emptyList())
    }

    override fun generate(
        toGenerate: FileSpec,
        settings: ISettings,
        originatingFiles: List<Any>,
        aggregating: Boolean,
    ) {
        ClassName(toGenerate.packageName, toGenerate.name).apply {
            ProcessingContext.createdQualifiedClassNames.add(this)
        }

        val ksFiles = originatingFiles.filterIsInstance<KSFile>()
        val dependencies = if (ksFiles.isNotEmpty()) {
            Dependencies(aggregating, *ksFiles.toTypedArray())
        } else {
            Dependencies(aggregating)
        }

        generationRecords.add(
            GenerationRecord(
                fileName = toGenerate.name,
                originatingFileNames = ksFiles.map { it.fileName },
                aggregating = aggregating,
            ),
        )

        val fileWithHeader = toGenerate.toBuilder().addFileComment(HEADER).build()
        val content = fileWithHeader.toString()
        if (cache != null &&
            !cache.shouldGenerate(fileWithHeader.packageName, fileWithHeader.name, content)
        ) {
            return
        }
        generator
            .createNewFile(
                dependencies,
                fileWithHeader.packageName,
                fileWithHeader.name,
            ).writer()
            .use { it.write(content) }
    }

    @Throws(IOException::class)
    override fun generateAndFixAccessors(
        entityToGenerate: FileSpec,
        generateAccessors: MutableList<CblGenerateAccessorHolder>,
        settings: ISettings,
    ) {
        generateAndFixAccessors(entityToGenerate, generateAccessors, settings, emptyList())
    }

    @Throws(IOException::class)
    override fun generateAndFixAccessors(
        entityToGenerate: FileSpec,
        generateAccessors: MutableList<CblGenerateAccessorHolder>,
        settings: ISettings,
        originatingFiles: List<Any>,
        aggregating: Boolean,
    ) {
        ClassName(entityToGenerate.packageName, entityToGenerate.name).apply {
            ProcessingContext.createdQualifiedClassNames.add(this)
        }

        val ksFiles = originatingFiles.filterIsInstance<KSFile>()
        val dependencies = if (ksFiles.isNotEmpty()) {
            Dependencies(aggregating, *ksFiles.toTypedArray())
        } else {
            Dependencies(aggregating)
        }

        generationRecords.add(
            GenerationRecord(
                fileName = entityToGenerate.name,
                originatingFileNames = ksFiles.map { it.fileName },
                aggregating = aggregating,
            ),
        )

        val fileWithHeader = entityToGenerate.toBuilder().addFileComment(HEADER).build()

        val fixedFileString =
            generateAccessors.fold(fileWithHeader.toString()) { acc, generateAccessor ->
                if (generateAccessor.memberFunction != null &&
                    generateAccessor.memberFunction?.isSuspend == true
                ) {
                    val escapedName = Regex.escape(generateAccessor.memberFunction?.name ?: "")
                    acc.replace(
                        Regex(
                            "($escapedName\\([^)]*\\)):\\s*Unit(\\s*=)",
                        ),
                        "$1$2",
                    )
                } else {
                    acc
                }
            }

        if (cache != null &&
            !cache.shouldGenerate(fileWithHeader.packageName, fileWithHeader.name, fixedFileString)
        ) {
            return
        }
        generator
            .createNewFile(
                dependencies,
                fileWithHeader.packageName,
                fileWithHeader.name,
            ).writer()
            .use { it.write(fixedFileString) }
    }

    companion object {
        private val HEADER = (
            "DO NOT EDIT THIS FILE.\n" +
                "Generated using Crystal-Map\n\n" +
                "Do not edit this class!!!!.\n"
        )
    }
}
