package com.kaufland.generation;

import com.helger.jcodemodel.writer.PrologCodeWriter;
import com.kaufland.model.EntityGenModel;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.UnsupportedCharsetException;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Element;

/**
 * Created by sbra0902 on 24.05.17.
 */

public class CodeGenerator {

    private final Filer filer;
    private final String encoding;

    private static final String HEADER = "DO NOT EDIT THIS FILE.\n"
            + "Generated using Couchbasebinder " + "Version" + ".\n\n"
            + "Do not edit this class!!!!.\n";

    public CodeGenerator(Filer filer, String encoding) {
        this.filer = filer;
        this.encoding = encoding;
    }

    public void generate(EntityGenModel model, Element ... elements) throws IOException {
        Charset charset = getCharset();

        SourceCodeWriter sourceCodeWriter = new SourceCodeWriter(filer, charset, elements);

        PrologCodeWriter prologWriter = new PrologCodeWriter(sourceCodeWriter, HEADER);

        model.generateModel().build(prologWriter);
    }

    private Charset getCharset() {
        try {
            return Charset.forName(encoding);
        } catch (UnsupportedCharsetException exception) {
            Charset defaultCharset = Charset.defaultCharset();
            return defaultCharset;
        }
    }

}
