package com.kaufland.generation;

import com.squareup.javapoet.JavaFile;

import java.io.IOException;

import javax.annotation.processing.Filer;

public class CodeGenerator {

    private final Filer filer;

    private static final String HEADER = "DO NOT EDIT THIS FILE.\n"
            + "Generated using Couchbasebinder\n\n"
            + "Do not edit this class!!!!.\n";

    public CodeGenerator(Filer filer) {
        this.filer = filer;
    }

    public void generate(JavaFile entityToGenerate) throws IOException {

        JavaFile fileWithHeader = entityToGenerate.
                toBuilder().
                addFileComment(HEADER).
                build();

        fileWithHeader.writeTo(filer);
    }
}
