package com.kaufland.generation

import com.squareup.kotlinpoet.FileSpec

import java.io.IOException

import javax.annotation.processing.Filer

class CodeGenerator(private val filer: Filer) {

    @Throws(IOException::class)
    fun generate(entityToGenerate: FileSpec) {

        val fileWithHeader = entityToGenerate.toBuilder().addComment(HEADER).build()

        fileWithHeader.writeTo(filer)
    }

    companion object {

        private val HEADER = ("DO NOT EDIT THIS FILE.\n"
                + "Generated using Couchbasebinder\n\n"
                + "Do not edit this class!!!!.\n")
    }
}
