apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace "com.schwarz.crystalcouchbaseconnector"
    compileSdk = 36

    defaultConfig {
        minSdk = 21

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

    }

    testOptions {
        targetSdk = 33
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    publishing {
        singleVariant('release')
    }
}



afterEvaluate {
    publishing {
        publications {
            maven(MavenPublication) {
                groupId groupName
                artifactId project.name
                version project.version
                from components.release
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    testImplementation("org.junit.jupiter:junit-jupiter-api:$junit_version")
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    compileOnly 'com.couchbase.lite:couchbase-lite-android:2.1.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation project(path: ':crystal-map-api')
}
